### ISSUE TITLE
TBA App ID

### ISSUE THREAD

**Issue by CarterFendley** [frc1418/tbarb#1]
Might not want to include your own TBA App ID if you are making this public. I would suggest making a function to set the ID

**Comment by ErikBoesen** [comment]
Is this something you're supposed to keep private? I agree it makes sense to make people use their own IDs, though.

**Comment by CarterFendley** [comment]
No not private. But if anyone else uses the API it will look like it is coming from you.

**Comment by ErikBoesen** [comment]
Yeah, I'll fix this in just a second.
